name: helpers
description: Helpers for a Flutter project, including state management, htpp, ui, theme brightness, testing, auth, etc.

publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: ^0.13.5
  rx_shared_preferences: ^3.0.0
  bloc: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  english_words: ^4.0.0
  fake_async: ^1.3.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true

